services:
  mongo:
    container_name: scrum-poker-online-mongo
    image: mongo:7
    ports:
      - '27017:27017'
  server:
    container_name: scum-poker-online-server
    build: ./docker/devServer
    working_dir: /app
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - mongo
